name: Test ShigEiFinder

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
    
jobs:
  shigeifinder:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: shigeifinder
          auto-activate-base: false
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true

      - name: Setup mamba env
        run: mamba install -y -c conda-forge -c bioconda 'fastq-dl>=2.0.2' 'python>=3.7.3' 'bwa>=0.7.17' 'samtools>=1.10' 'blast >=2.9.0'

      - name: Environment Information
        run: uname -a && env

      - name: Test Usage and Version
        run: |
          python3 -m shigeifinder.shigeifinder --help
          python3 -m shigeifinder.shigeifinder --version

      - name: Test ShigEiFinder with paired-end reads
        run: |
          fastq-dl -a SRX5006488 --group-by-experiment
          python3 -m shigeifinder.shigeifinder -r -i SRX5006488_R1.fastq.gz SRX5006488_R2.fastq.gz -t 2

      - name: Test ShigEiFinder with single-end reads
        run: |
          cat SRX5006488_R1.fastq.gz SRX5006488_R2.fastq.gz > SRX5006488SE.fastq.gz
          python3 -m shigeifinder.shigeifinder -r --single_end -i SRX5006488SE.fastq.gz

      - name: Test ShigEiFinder with optional output filename
        run: |
          cat SRX5006488_R1.fastq.gz SRX5006488_R2.fastq.gz > SRX5006488SE.fastq.gz
          python3 -m shigeifinder.shigeifinder -r --single_end -i SRX5006488SE.fastq.gz --output SRX5006488.tsv
          ls "SRX5006488.tsv"

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10052838
      - name: Test ShigEiFinder with a Shigella flexneri serotype 1a
        run: |
          fastq-dl -a SRR8186648 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186648_1.fastq.gz SRR8186648_2.fastq.gz --output SRR8186648.tsv
          cat SRR8186648.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040580
      - name: Test ShigEiFinder with a Shigella flexneri serotype 1b
        run: |
          fastq-dl -a SRR8186627 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186627_1.fastq.gz SRR8186627_2.fastq.gz --output SRR8186627.tsv
          cat SRR8186627.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040584
      - name: Test ShigEiFinder with a Shigella flexneri serotype 2a
        run: |
          fastq-dl -a SRR8186705 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186705_1.fastq.gz SRR8186705_2.fastq.gz --output SRR8186705.tsv
          cat SRR8186705.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040583
      - name: Test ShigEiFinder with a Shigella flexneri serotype 2b
        run: |
          fastq-dl -a SRR8186704 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186704_1.fastq.gz SRR8186704_2.fastq.gz --output SRR8186704.tsv
          cat SRR8186704.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10052840
      - name: Test ShigEiFinder with a Shigella flexneri serotype 3a
        run: |
          fastq-dl -a SRR8186651 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186651_1.fastq.gz SRR8186651_2.fastq.gz --output SRR8186651.tsv
          cat SRR8186651.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040645
      - name: Test ShigEiFinder with a Shigella flexneri serotype 3b
        run: |
          fastq-dl -a SRR8186727 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186727_1.fastq.gz SRR8186727_2.fastq.gz --output SRR8186727.tsv
          cat SRR8186727.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040581
      - name: Test ShigEiFinder with a Shigella flexneri serotype Xv (4c)
        run: |
          fastq-dl -a SRR8186631 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186631_1.fastq.gz SRR8186631_2.fastq.gz --output SRR8186631.tsv
          cat SRR8186631.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN03291463
      # this sample was not in Shigatyper paper, I found it randomly on NCBI
      - name: Test ShigEiFinder with a Shigella flexneri serotype 5a
        run: |
          fastq-dl -a SRR1811686 
          python3 -m shigeifinder.shigeifinder -r -i SRR1811686_1.fastq.gz SRR1811686_2.fastq.gz --output SRR1811686.tsv
          cat SRR1811686.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10052842
      - name: Test ShigEiFinder with a Shigella flexneri serotype Y
        run: |
          fastq-dl -a SRR8186645
          python3 -m shigeifinder.shigeifinder -r -i SRR8186645_1.fastq.gz SRR8186645_2.fastq.gz --output SRR8186645.tsv
          cat SRR8186645.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040648
      - name: Test ShigEiFinder with a Shigella flexneri serotype 6
        run: |
          fastq-dl -a SRR8186591 
          python3 -m shigeifinder.shigeifinder -r -i SRR8186591_1.fastq.gz SRR8186591_2.fastq.gz --output SRR8186591.tsv
          cat SRR8186591.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10040589
      - name: Test ShigEiFinder with a Shigella flexneri serotype 1c (7a)
        run: |
          fastq-dl -a SRR8186684
          python3 -m shigeifinder.shigeifinder -r -i SRR8186684_1.fastq.gz SRR8186684_2.fastq.gz --output SRR8186684.tsv
          cat SRR8186684.tsv

      # BioSample: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN10052844
      - name: Test ShigEiFinder with a Shigella flexneri serotype 7b
        run: |
          fastq-dl -a SRR8186647
          python3 -m shigeifinder.shigeifinder -r -i SRR8186647_1.fastq.gz SRR8186647_2.fastq.gz --output SRR8186647.tsv
          cat SRR8186647.tsv